image = "lmsysorg/sglang:v0.5.10"

mounts = [
  "/capstor:/capstor",
  "/iopsstor:/iopsstor",
]

workdir = "/iopsstor/scratch/cscs/yboughizane/simple-serving-stack/examples/fast-weight-load"

[env]
HOME = "/root"
NCCL_DEBUG = "WARN"
PYTHONPATH = ""
PYTHONNOUSERSITE = "1"
HF_HUB_OFFLINE = "1"
TRANSFORMERS_OFFLINE = "1"
TOKENIZERS_PARALLELISM = "false"

[annotations]
com.pyxis.entrypoint_log = "true"
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"
